{
//=========Macro generated from canvas: c/c
//=========  (Thu Jul 10 15:00:24 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(10483.87,-270.9,107258.1,13274.1);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetLeftMargin(0.15);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0.02);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   
   THStack *mc_jetpt = new THStack();
   mc_jetpt->SetName("mc_jetpt");
   mc_jetpt->SetTitle("mc_jetpt");
   mc_jetpt->SetMinimum(0);
   mc_jetpt->SetMaximum(11997);
   Double_t xAxis337[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1F *mc_jetpt_stack_49 = new TH1F("mc_jetpt_stack_49","mc_jetpt",8, xAxis337);
   mc_jetpt_stack_49->SetMinimum(0);
   mc_jetpt_stack_49->SetMaximum(12596.85);
   mc_jetpt_stack_49->SetDirectory(0);
   mc_jetpt_stack_49->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   mc_jetpt_stack_49->SetLineColor(ci);
   mc_jetpt_stack_49->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   mc_jetpt_stack_49->GetXaxis()->SetLabelFont(42);
   mc_jetpt_stack_49->GetXaxis()->SetLabelSize(0);
   mc_jetpt_stack_49->GetXaxis()->SetTitleSize(0);
   mc_jetpt_stack_49->GetXaxis()->SetTitleFont(42);
   mc_jetpt_stack_49->GetYaxis()->SetTitle("entries");
   mc_jetpt_stack_49->GetYaxis()->SetLabelFont(42);
   mc_jetpt_stack_49->GetYaxis()->SetLabelSize(0.035);
   mc_jetpt_stack_49->GetYaxis()->SetTitleSize(0.06);
   mc_jetpt_stack_49->GetYaxis()->SetTitleFont(42);
   mc_jetpt_stack_49->GetZaxis()->SetLabelFont(42);
   mc_jetpt_stack_49->GetZaxis()->SetLabelSize(0.035);
   mc_jetpt_stack_49->GetZaxis()->SetTitleSize(0.035);
   mc_jetpt_stack_49->GetZaxis()->SetTitleFont(42);
   mc_jetpt->SetHistogram(mc_jetpt_stack_49);
   
   Double_t xAxis338[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97 = new TH1D("jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97","BKG",8, xAxis338);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(1,1516.3);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(2,1055.177);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(3,830.1009);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(4,613.8301);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(5,432.8702);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(6,678.3995);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(7,800.3796);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(8,1543.509);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(1,105.2445);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(2,85.51959);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(3,73.14844);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(4,63.0025);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(5,54.64786);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(6,65.8119);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(7,61.53945);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(8,57.52078);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetEntries(1863.344);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetDirectory(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetLineColor(ci);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetLineWidth(2);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetXaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetXaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetXaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetXaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetYaxis()->SetTitle("entries");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetYaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetYaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetYaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetYaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetZaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetZaxis()->SetTitleFont(42);
   mc_jetpt->Add(jetpt_data_temp_peak_tag_PeriodA_physics_Egamma,"");
   Double_t xAxis339[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98 = new TH1D("jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98","MC",8, xAxis339);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(1,9812.873);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(2,6977.602);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(3,5234.737);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(4,3805.205);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(5,2906.858);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(6,4226.407);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(7,3613.731);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(8,3239.454);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(1,121.0027);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(2,88.33394);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(3,71.12304);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(4,56.25622);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(5,47.07465);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(6,64.63552);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(7,56.63046);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(8,50.47815);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetEntries(115135);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetDirectory(0);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetLineColor(ci);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetLineWidth(2);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetXaxis()->SetLabelFont(42);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetXaxis()->SetLabelSize(0.035);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetXaxis()->SetTitleSize(0.035);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetXaxis()->SetTitleFont(42);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetYaxis()->SetTitle("entries");
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetYaxis()->SetLabelFont(42);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetYaxis()->SetLabelSize(0.035);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetYaxis()->SetTitleSize(0.035);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetYaxis()->SetTitleFont(42);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetZaxis()->SetLabelFont(42);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetZaxis()->SetLabelSize(0.035);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetZaxis()->SetTitleSize(0.035);
   jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetZaxis()->SetTitleFont(42);
   mc_jetpt->Add(jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l,"");
   mc_jetpt->Draw("ehist");
   Double_t xAxis340[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("jetpt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis340);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,11329.17);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,8032.778);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,6064.838);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,4419.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,3339.728);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,4904.807);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,4414.11);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,4782.962);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,160.3685);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,122.9491);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,102.0254);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,84.46347);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,72.12774);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,92.24401);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,83.63081);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,76.52897);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(116998.3);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   Double_t xAxis341[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma = new TH1D("jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis341);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(1,11997);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(2,8005);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(3,5876);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(4,4378);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(5,3281);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(6,4808);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(7,4409);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(8,4673);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(1,109.5308);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(2,89.47067);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(3,76.65507);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(4,66.16646);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(5,57.28001);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(6,69.33974);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(7,66.4003);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(8,68.35934);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetEntries(47467);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetStats(0);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->Draw("esame");
   
   TLegend *leg = new TLegend(0.6,0.6,0.75,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("jetpt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.75,0.6,0.9,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("jetpt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.675,0.5,0.825,0.6,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma","data","lpe");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(10483.87,0.05882352,107258.1,1.529412);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetLeftMargin(0.15);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0.02);
   c_2->SetBottomMargin(0.3);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis342[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma = new TH1D("jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis342);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(1,1.058948);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.9965419);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.9688635);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(4,0.9907141);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.9824152);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.9802629);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(7,0.9988423);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.9770096);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.01783716);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.01888686);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.02062515);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.02414057);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02728234);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.02323212);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.02417465);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.02118119);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetMinimum(0.5);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetMaximum(1.5);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetEntries(15814.31);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetStats(0);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.75);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("data/prediction");
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   jetpt_data_tag_loose_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis343[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("jetpt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis343);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,0.0200187);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,0.02164585);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,0.02379053);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,0.02703065);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,0.03054261);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,0.02659692);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,0.02679404);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,0.02262788);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(12708.18);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   TLine *line = new TLine(25000,1,100000,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
