{
//=========Macro generated from canvas: c/c
//=========  (Sun Jun 29 15:51:56 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(-3.068788,0,2.919091,5511.792);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   
   THStack *mc_eta = new THStack();
   mc_eta->SetName("mc_eta");
   mc_eta->SetTitle("mc_eta");
   mc_eta->SetMinimum(0);
   mc_eta->SetMaximum(4986.86);
   Double_t xAxis127[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1F *mc_eta_stack_19 = new TH1F("mc_eta_stack_19","mc_eta",14, xAxis127);
   mc_eta_stack_19->SetMinimum(0);
   mc_eta_stack_19->SetMaximum(5236.203);
   mc_eta_stack_19->SetDirectory(0);
   mc_eta_stack_19->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   mc_eta_stack_19->SetLineColor(ci);
   mc_eta_stack_19->GetXaxis()->SetTitle("#eta");
   mc_eta_stack_19->GetXaxis()->SetLabelFont(42);
   mc_eta_stack_19->GetXaxis()->SetLabelSize(0);
   mc_eta_stack_19->GetXaxis()->SetTitleSize(0);
   mc_eta_stack_19->GetXaxis()->SetTitleFont(42);
   mc_eta_stack_19->GetYaxis()->SetTitle("entries");
   mc_eta_stack_19->GetYaxis()->SetLabelFont(42);
   mc_eta_stack_19->GetYaxis()->SetLabelSize(0.035);
   mc_eta_stack_19->GetYaxis()->SetTitleSize(0.06);
   mc_eta_stack_19->GetYaxis()->SetTitleOffset(0.7);
   mc_eta_stack_19->GetYaxis()->SetTitleFont(42);
   mc_eta_stack_19->GetZaxis()->SetLabelFont(42);
   mc_eta_stack_19->GetZaxis()->SetLabelSize(0.035);
   mc_eta_stack_19->GetZaxis()->SetTitleSize(0.035);
   mc_eta_stack_19->GetZaxis()->SetTitleFont(42);
   mc_eta->SetHistogram(mc_eta_stack_19);
   
   Double_t xAxis128[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_temp_peak_tag_PeriodA_physics_Egamma__37 = new TH1D("eta_data_temp_peak_tag_PeriodA_physics_Egamma__37","BKG",14, xAxis128);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(1,3.123245);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(2,0.805537);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(4,1.652253);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(5,4.109335);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(6,1.572626);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(7,0.9373234);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(8,-0.2463119);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(9,2.85039);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(10,1.536924);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(11,2.315258);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(13,1.626514);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(14,2.77735);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(1,1.572247);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(2,0.7108638);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(4,1.293428);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(5,1.62163);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(6,1.149203);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(7,0.7045738);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(8,0.2012867);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(9,1.596905);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(10,1.486778);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(11,1.21659);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(13,1.123361);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(14,1.716813);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetEntries(27.14897);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetDirectory(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetLineColor(ci);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetLineWidth(2);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetXaxis()->SetTitle("#eta");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetXaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetXaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetXaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetXaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetYaxis()->SetTitle("entries");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetYaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetYaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetYaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetYaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetZaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetZaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetZaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetZaxis()->SetTitleFont(42);
   mc_eta->Add(eta_data_temp_peak_tag_PeriodA_physics_Egamma,"");
   Double_t xAxis129[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38 = new TH1D("eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38","MC",14, xAxis129);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(1,2037.209);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(2,1408.111);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(4,1484.58);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(5,4521.327);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(6,4985.287);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(7,922.9537);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(8,905.0496);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(9,4950.788);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(10,4681.756);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(11,1511.925);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(13,1426.936);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(14,2149.078);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(1,40.99203);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(2,34.52748);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(4,35.25807);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(5,67.47347);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(6,71.47525);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(7,27.49934);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(8,28.2105);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(9,70.8235);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(10,68.72265);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(11,35.00962);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(13,33.529);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(14,43.99989);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetEntries(89221);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetDirectory(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetLineColor(ci);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetLineWidth(2);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetXaxis()->SetTitle("#eta");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetXaxis()->SetLabelFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetXaxis()->SetLabelSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetXaxis()->SetTitleSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetXaxis()->SetTitleFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetYaxis()->SetTitle("entries");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetYaxis()->SetLabelFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetYaxis()->SetLabelSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetYaxis()->SetTitleSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetYaxis()->SetTitleFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetZaxis()->SetLabelFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetZaxis()->SetLabelSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetZaxis()->SetTitleSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetZaxis()->SetTitleFont(42);
   mc_eta->Add(eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l,"");
   mc_eta->Draw("ehist");
   Double_t xAxis130[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("eta_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",14, xAxis130);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,2040.332);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,1408.917);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,1486.232);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,4525.436);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,4986.86);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,923.891);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,904.8033);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(9,4953.638);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(10,4683.293);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(11,1514.24);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(13,1428.563);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(14,2151.855);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,41.02217);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,34.53479);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,35.28178);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,67.49296);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,71.48448);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,27.50837);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,28.21122);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(9,70.84151);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(10,68.73873);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(11,35.03076);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(13,33.54781);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(14,44.03337);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(89248.15);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#eta");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   Double_t xAxis131[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("eta_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",14, xAxis131);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,1930);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,1307);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,1543);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,4748);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,4913);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,1008);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,897);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(9,4920);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(10,4746);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(11,1567);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(13,1431);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(14,1975);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,43.93177);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,36.15245);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,39.28104);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,68.90573);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,70.0928);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,31.74902);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,29.94996);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(9,70.14271);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(10,68.89122);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(11,39.58535);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(13,37.82856);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(14,44.44097);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(31025);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#eta");
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("esame");
   
   TLegend *leg = new TLegend(0.6,0.6,0.75,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.75,0.6,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("eta_data_temp_peak_tag_PeriodA_physics_Egamma","BKG","lf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.675,0.5,0.825,0.6,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("eta_data_tag_tight_os_peak_PeriodA_physics_Egamma","data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(-3.068788,0.3095238,2.919091,1.5);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0);
   c_2->SetBottomMargin(0.16);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis132[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("eta_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",14, xAxis132);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,0.9459244);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.9276629);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,1.038196);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,1.049181);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.9851891);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,1.091038);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.9913757);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(9,0.9932094);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(10,1.01339);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(11,1.034842);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(13,1.001706);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(14,0.9178127);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.02872826);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.03428501);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.03613804);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02183321);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.01992474);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.04728844);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.04528951);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(9,0.02005614);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(10,0.02091934);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(11,0.03544775);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(13,0.03541979);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(14,0.02791513);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMinimum(0.5);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMaximum(1.5);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(11410.46);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#eta");
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.5);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("data/prediction");
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis133[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("eta_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",14, xAxis133);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(9,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(10,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(11,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(13,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(14,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,0.02843366);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,0.03466462);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,0.03357213);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,0.02109177);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,0.02027214);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,0.04210746);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,0.04409432);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(9,0.02022453);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(10,0.02075703);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(11,0.03271672);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(13,0.03321084);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(14,0.02893902);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(12455.6);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#eta");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   TLine *line = new TLine(-2.47,1,2.47,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
