{
//=========Macro generated from canvas: c/c
//=========  (Thu Jul 10 15:00:34 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(10483.87,-187.0355,107258.1,9164.739);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetLeftMargin(0.15);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0.02);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   
   THStack *mc_jetpt = new THStack();
   mc_jetpt->SetName("mc_jetpt");
   mc_jetpt->SetTitle("mc_jetpt");
   mc_jetpt->SetMinimum(0);
   mc_jetpt->SetMaximum(8283);
   Double_t xAxis337[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1F *mc_jetpt_stack_49 = new TH1F("mc_jetpt_stack_49","mc_jetpt",8, xAxis337);
   mc_jetpt_stack_49->SetMinimum(0);
   mc_jetpt_stack_49->SetMaximum(8697.15);
   mc_jetpt_stack_49->SetDirectory(0);
   mc_jetpt_stack_49->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   mc_jetpt_stack_49->SetLineColor(ci);
   mc_jetpt_stack_49->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   mc_jetpt_stack_49->GetXaxis()->SetLabelFont(42);
   mc_jetpt_stack_49->GetXaxis()->SetLabelSize(0);
   mc_jetpt_stack_49->GetXaxis()->SetTitleSize(0);
   mc_jetpt_stack_49->GetXaxis()->SetTitleFont(42);
   mc_jetpt_stack_49->GetYaxis()->SetTitle("entries");
   mc_jetpt_stack_49->GetYaxis()->SetLabelFont(42);
   mc_jetpt_stack_49->GetYaxis()->SetLabelSize(0.035);
   mc_jetpt_stack_49->GetYaxis()->SetTitleSize(0.06);
   mc_jetpt_stack_49->GetYaxis()->SetTitleFont(42);
   mc_jetpt_stack_49->GetZaxis()->SetLabelFont(42);
   mc_jetpt_stack_49->GetZaxis()->SetLabelSize(0.035);
   mc_jetpt_stack_49->GetZaxis()->SetTitleSize(0.035);
   mc_jetpt_stack_49->GetZaxis()->SetTitleFont(42);
   mc_jetpt->SetHistogram(mc_jetpt_stack_49);
   
   Double_t xAxis338[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97 = new TH1D("jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97","BKG",8, xAxis338);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(1,7.596069);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(2,3.912503);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(3,0.4956304);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(4,0.9571513);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(5,1.155994);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(6,3.974468);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(7,3.493241);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinContent(8,3.65463);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(1,2.865639);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(2,1.92207);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(3,1.128324);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(4,1.44723);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(5,0.980472);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(6,1.78855);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(7,1.853383);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetBinError(8,1.403097);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetEntries(25.6481);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetDirectory(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetLineColor(ci);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->SetLineWidth(2);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetXaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetXaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetXaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetXaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetYaxis()->SetTitle("entries");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetYaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetYaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetYaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetYaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetZaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma__97->GetZaxis()->SetTitleFont(42);
   mc_jetpt->Add(jetpt_data_temp_peak_tag_PeriodA_physics_Egamma,"");
   Double_t xAxis339[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98 = new TH1D("jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98","MC",8, xAxis339);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(1,7796.183);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(2,5499.028);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(3,4070.717);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(4,2917.278);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(5,2221.923);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(6,3250.952);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(7,2753.5);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinContent(8,2475.42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(1,103.9089);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(2,75.5772);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(3,60.56478);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(4,47.69874);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(5,40.43846);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(6,55.39354);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(7,47.96972);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetBinError(8,42.99817);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetEntries(89215);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetDirectory(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetLineColor(ci);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->SetLineWidth(2);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetXaxis()->SetLabelFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetXaxis()->SetLabelSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetXaxis()->SetTitleSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetXaxis()->SetTitleFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetYaxis()->SetTitle("entries");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetYaxis()->SetLabelFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetYaxis()->SetLabelSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetYaxis()->SetTitleSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetYaxis()->SetTitleFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetZaxis()->SetLabelFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetZaxis()->SetLabelSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetZaxis()->SetTitleSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__98->GetZaxis()->SetTitleFont(42);
   mc_jetpt->Add(jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l,"");
   mc_jetpt->Draw("ehist");
   Double_t xAxis340[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("jetpt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis340);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,7803.779);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,5502.941);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,4071.212);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,2918.235);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,2223.079);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,3254.926);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,2756.993);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,2479.075);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,103.9484);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,75.60164);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,60.57529);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,47.72069);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,40.45034);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,55.42241);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,48.00551);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,43.02105);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(89240.65);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   Double_t xAxis341[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis341);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,8283);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,5453);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,3968);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,2922);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,2177);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,3149);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,2729);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,2304);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,91.01099);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,73.84443);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,62.99206);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,54.05553);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,46.65833);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,56.11595);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,52.23983);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,48);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(31025);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("esame");
   
   TLegend *leg = new TLegend(0.6,0.6,0.75,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.75,0.6,0.9,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("jetpt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.675,0.5,0.825,0.6,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma","data","lpe");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(10483.87,0.05882352,107258.1,1.529412);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetLeftMargin(0.15);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0.02);
   c_2->SetBottomMargin(0.3);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis342[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis342);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,1.061409);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.9909247);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.9746483);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,1.00129);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.9792726);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.9674567);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,0.9898465);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.929379);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.01832763);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.01911558);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.02120613);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.02472272);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02753183);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.02384517);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.02561431);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.02519933);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMinimum(0.5);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMaximum(1.5);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(14228.32);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.75);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("data/prediction");
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis343[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("jetpt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis343);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,0.0188377);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,0.01942904);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,0.02104199);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,0.02312605);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,0.02573252);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,0.02408015);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,0.02462467);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,0.0245418);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(15382.33);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   jetpt_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   TLine *line = new TLine(25000,1,100000,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
