{
//=========Macro generated from canvas: c/c
//=========  (Thu Jul 10 15:00:17 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(10483.87,-350.2935,107258.1,17164.38);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetLeftMargin(0.15);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0.02);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   
   THStack *mc_pt = new THStack();
   mc_pt->SetName("mc_pt");
   mc_pt->SetTitle("mc_pt");
   mc_pt->SetMinimum(0);
   mc_pt->SetMaximum(15513);
   Double_t xAxis1[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1F *mc_pt_stack_1 = new TH1F("mc_pt_stack_1","mc_pt",8, xAxis1);
   mc_pt_stack_1->SetMinimum(0);
   mc_pt_stack_1->SetMaximum(16288.65);
   mc_pt_stack_1->SetDirectory(0);
   mc_pt_stack_1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   mc_pt_stack_1->SetLineColor(ci);
   mc_pt_stack_1->GetXaxis()->SetTitle("p_{T} [MeV]");
   mc_pt_stack_1->GetXaxis()->SetLabelFont(42);
   mc_pt_stack_1->GetXaxis()->SetLabelSize(0);
   mc_pt_stack_1->GetXaxis()->SetTitleSize(0);
   mc_pt_stack_1->GetXaxis()->SetTitleFont(42);
   mc_pt_stack_1->GetYaxis()->SetTitle("entries");
   mc_pt_stack_1->GetYaxis()->SetLabelFont(42);
   mc_pt_stack_1->GetYaxis()->SetLabelSize(0.035);
   mc_pt_stack_1->GetYaxis()->SetTitleSize(0.06);
   mc_pt_stack_1->GetYaxis()->SetTitleFont(42);
   mc_pt_stack_1->GetZaxis()->SetLabelFont(42);
   mc_pt_stack_1->GetZaxis()->SetLabelSize(0.035);
   mc_pt_stack_1->GetZaxis()->SetTitleSize(0.035);
   mc_pt_stack_1->GetZaxis()->SetTitleFont(42);
   mc_pt->SetHistogram(mc_pt_stack_1);
   
   Double_t xAxis2[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_temp_peak_tag_PeriodA_physics_Egamma__1 = new TH1D("pt_data_temp_peak_tag_PeriodA_physics_Egamma__1","BKG",8, xAxis2);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(1,2318.451);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(2,1387.4);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(3,853.0275);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(4,496.9046);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(5,369.1656);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(6,396.0162);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(7,283.0624);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(8,156.918);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(1,115.4949);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(2,102.2037);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(3,79.56653);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(4,64.24658);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(5,50.10946);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(6,49.9063);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(7,42.14594);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(8,33.14236);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetEntries(1836.275);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetDirectory(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetLineColor(ci);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetLineWidth(2);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetXaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetXaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetXaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetXaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetYaxis()->SetTitle("entries");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetYaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetYaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetYaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetYaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetZaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetZaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetZaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetZaxis()->SetTitleFont(42);
   mc_pt->Add(pt_data_temp_peak_tag_PeriodA_physics_Egamma,"");
   Double_t xAxis3[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2 = new TH1D("pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2","MC",8, xAxis3);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(1,12549.47);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(2,10090.94);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(3,6289.41);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(4,3689.612);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(5,2239.528);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(6,2188.113);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(7,1624.668);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(8,1145.122);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(1,129.9163);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(2,113.2425);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(3,88.64378);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(4,65.98092);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(5,50.1262);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(6,40.83372);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(7,32.45878);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(8,26.72037);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetEntries(115135);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetDirectory(0);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetLineColor(ci);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetLineWidth(2);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetXaxis()->SetLabelFont(42);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetXaxis()->SetLabelSize(0.035);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetXaxis()->SetTitleSize(0.035);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetXaxis()->SetTitleFont(42);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetYaxis()->SetTitle("entries");
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetYaxis()->SetLabelFont(42);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetYaxis()->SetLabelSize(0.035);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetYaxis()->SetTitleSize(0.035);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetYaxis()->SetTitleFont(42);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetZaxis()->SetLabelFont(42);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetZaxis()->SetLabelSize(0.035);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetZaxis()->SetTitleSize(0.035);
   pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetZaxis()->SetTitleFont(42);
   mc_pt->Add(pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l,"");
   mc_pt->Draw("ehist");
   Double_t xAxis4[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("pt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis4);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,14867.92);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,11478.34);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,7142.438);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,4186.517);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,2608.694);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,2584.129);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1907.73);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,1302.04);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,173.8313);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,152.5432);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,119.1157);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,92.09291);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,70.87731);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,64.4828);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,53.19636);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,42.57222);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(116971.3);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   Double_t xAxis5[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_tag_loose_os_peak_PeriodA_physics_Egamma = new TH1D("pt_data_tag_loose_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis5);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(1,15513);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(2,11677);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(3,7067);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(4,4527);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(5,2777);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(6,2760);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(7,1945);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(8,1161);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(1,124.5512);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(2,108.0602);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(3,84.06545);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(4,67.28298);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(5,52.69725);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(6,52.5357);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(7,44.10215);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(8,34.07345);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetEntries(47467);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetStats(0);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->Draw("esame");
   
   TLegend *leg = new TLegend(0.6,0.6,0.75,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("pt_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.75,0.6,0.9,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("pt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.675,0.5,0.825,0.6,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("pt_data_tag_loose_os_peak_PeriodA_physics_Egamma","data","lpe");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(10483.87,0.05882352,107258.1,1.529412);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetLeftMargin(0.15);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0.02);
   c_2->SetBottomMargin(0.3);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis6[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_tag_loose_os_peak_PeriodA_physics_Egamma = new TH1D("pt_data_tag_loose_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis6);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(1,1.043387);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(2,1.017307);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.9894381);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(4,1.081328);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(5,1.064517);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(6,1.068058);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(7,1.019536);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.8916779);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.01479838);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.01647451);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.02026854);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.02870692);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.03527861);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.03352053);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.03664224);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.03917696);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetMinimum(0.5);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetMaximum(1.5);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetEntries(9587.542);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetStats(0);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.75);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("data/prediction");
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   pt_data_tag_loose_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis7[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("pt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis7);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,0.01653457);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,0.01879441);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,0.02358509);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,0.03110917);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,0.03842369);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,0.03528943);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,0.03943482);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,0.04623992);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(7471.732);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   TLine *line = new TLine(25000,1,100000,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
