{
//=========Macro generated from canvas: c/c
//=========  (Thu Jul 10 15:15:29 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(15909.09,-0.02365591,106818.2,1.15914);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0.02);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   Double_t xAxis1[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l = new TH1D("pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC",8, xAxis1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(1,0.74484);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(2,0.7759823);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(3,0.7880685);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(4,0.7848572);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(5,0.8110693);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(6,0.8118946);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(7,0.8391628);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(8,0.872103);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(1,0.005590676);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(2,0.005393509);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(3,0.006292217);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(4,0.007620744);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(5,0.00920245);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(6,0.007498396);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(7,0.007914665);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(8,0.008269891);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMinimum(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMaximum(1.1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetEntries(115135);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetStats(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetFillStyle(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineColor(ci);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineStyle(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerColor(ci);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerStyle(22);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelSize(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleSize(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitle("Efficiency");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleSize(0.06);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleOffset(0.7);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->Draw("pe");
   Double_t xAxis2[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("pt_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis2);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,0.7184046);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.7501194);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.7694095);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,0.7540339);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.7726098);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.7897511);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,0.8139217);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.865535);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.0164989);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.01074234);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.01999237);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.01471305);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02433342);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.02042964);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.0257131);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.0339709);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(18924.76);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetFillStyle(0);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineStyle(0);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMarkerStyle(23);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("Efficiency");
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("pesame");
   
   TLegend *leg = new TLegend(0.6,0.3,0.75,0.5,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("pt_data_tag_tight_os_peak_PeriodA_physics_Egamma","data","lpe");
   entry->SetLineColor(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(23);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lpe");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(15909.09,0.6235294,106818.2,1.211765);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0.02);
   c_2->SetBottomMargin(0.3);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis3[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("pt_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis3);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,0.9645085);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.9666708);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.9763231);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,0.9607275);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.9525817);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.9727261);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,0.9699211);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.9924688);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.02330394);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.01538788);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.02653948);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.02093889);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.03188908);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.02671855);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.03197778);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.04007365);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMinimum(0.8);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMaximum(1.2);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(9575.813);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetFillStyle(0);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineStyle(0);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMarkerStyle(23);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.85);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("Data/MC");
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis4[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l = new TH1D("pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC",8, xAxis4);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(1,1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(2,1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(3,1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(4,1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(5,1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(6,1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(7,1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(8,1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(1,0.01061491);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(2,0.009829572);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(3,0.01129158);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(4,0.01373162);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(5,0.01604577);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(6,0.01306122);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(7,0.01333833);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(8,0.01341056);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMinimum(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMaximum(1.1);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetEntries(48811.36);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetStats(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetFillStyle(0);

   ci = TColor::GetColor("#0000ff");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineColor(ci);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineStyle(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerColor(ci);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerStyle(22);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerSize(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelSize(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleSize(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitle("Efficiency");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleSize(0.06);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleOffset(0.7);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->Draw("e2same");
   TLine *line = new TLine(25000,1,100000,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
