{
//=========Macro generated from canvas: c/c
//=========  (Sun Jun 29 15:51:47 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(-3.068788,0,2.919091,8382.316);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   
   THStack *mc_eta = new THStack();
   mc_eta->SetName("mc_eta");
   mc_eta->SetTitle("mc_eta");
   mc_eta->SetMinimum(0);
   mc_eta->SetMaximum(7584);
   Double_t xAxis127[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1F *mc_eta_stack_19 = new TH1F("mc_eta_stack_19","mc_eta",14, xAxis127);
   mc_eta_stack_19->SetMinimum(0);
   mc_eta_stack_19->SetMaximum(7963.2);
   mc_eta_stack_19->SetDirectory(0);
   mc_eta_stack_19->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   mc_eta_stack_19->SetLineColor(ci);
   mc_eta_stack_19->GetXaxis()->SetTitle("#eta");
   mc_eta_stack_19->GetXaxis()->SetLabelFont(42);
   mc_eta_stack_19->GetXaxis()->SetLabelSize(0);
   mc_eta_stack_19->GetXaxis()->SetTitleSize(0);
   mc_eta_stack_19->GetXaxis()->SetTitleFont(42);
   mc_eta_stack_19->GetYaxis()->SetTitle("entries");
   mc_eta_stack_19->GetYaxis()->SetLabelFont(42);
   mc_eta_stack_19->GetYaxis()->SetLabelSize(0.035);
   mc_eta_stack_19->GetYaxis()->SetTitleSize(0.06);
   mc_eta_stack_19->GetYaxis()->SetTitleOffset(0.7);
   mc_eta_stack_19->GetYaxis()->SetTitleFont(42);
   mc_eta_stack_19->GetZaxis()->SetLabelFont(42);
   mc_eta_stack_19->GetZaxis()->SetLabelSize(0.035);
   mc_eta_stack_19->GetZaxis()->SetTitleSize(0.035);
   mc_eta_stack_19->GetZaxis()->SetTitleFont(42);
   mc_eta->SetHistogram(mc_eta_stack_19);
   
   Double_t xAxis128[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_temp_peak_tag_PeriodA_physics_Egamma__37 = new TH1D("eta_data_temp_peak_tag_PeriodA_physics_Egamma__37","BKG",14, xAxis128);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(1,352.7086);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(2,228.5838);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(4,309.9103);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(5,1075.99);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(6,1342.758);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(7,275.6305);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(8,299.8097);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(9,1374.096);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(10,955.5408);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(11,324.7238);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(13,244.9926);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinContent(14,351.1761);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(1,52.5814);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(2,42.63018);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(4,46.27728);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(5,79.4535);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(6,81.16854);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(7,37.74217);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(8,36.67924);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(9,80.96798);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(10,79.83066);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(11,46.14631);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(13,43.99196);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetBinError(14,52.32607);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetEntries(2031.262);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetDirectory(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetLineColor(ci);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->SetLineWidth(2);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetXaxis()->SetTitle("#eta");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetXaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetXaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetXaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetXaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetYaxis()->SetTitle("entries");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetYaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetYaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetYaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetYaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetZaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetZaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetZaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma__37->GetZaxis()->SetTitleFont(42);
   mc_eta->Add(eta_data_temp_peak_tag_PeriodA_physics_Egamma,"");
   Double_t xAxis129[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38 = new TH1D("eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38","MC",14, xAxis129);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(1,2661.075);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(2,1883.84);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(4,2012.498);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(5,5763.32);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(6,6141.044);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(7,1265.499);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(8,1285.472);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(9,6161.638);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(10,5926.174);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(11,2035.086);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(13,1896.381);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinContent(14,2784.839);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(1,47.37575);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(2,40.19896);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(4,41.6428);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(5,78.89852);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(6,81.42561);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(7,31.85646);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(8,33.69438);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(9,81.58153);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(10,79.50733);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(11,41.13931);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(13,39.78293);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetBinError(14,51.22349);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetEntries(115141);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetDirectory(0);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetLineColor(ci);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->SetLineWidth(2);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetXaxis()->SetTitle("#eta");
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetXaxis()->SetLabelFont(42);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetXaxis()->SetLabelSize(0.035);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetXaxis()->SetTitleSize(0.035);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetXaxis()->SetTitleFont(42);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetYaxis()->SetTitle("entries");
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetYaxis()->SetLabelFont(42);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetYaxis()->SetLabelSize(0.035);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetYaxis()->SetTitleSize(0.035);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetYaxis()->SetTitleFont(42);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetZaxis()->SetLabelFont(42);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetZaxis()->SetLabelSize(0.035);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetZaxis()->SetTitleSize(0.035);
   eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__38->GetZaxis()->SetTitleFont(42);
   mc_eta->Add(eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l,"");
   mc_eta->Draw("ehist");
   Double_t xAxis130[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("eta_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",14, xAxis130);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,3013.783);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,2112.424);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,2322.408);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,6839.31);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,7483.802);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1541.129);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,1585.282);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(9,7535.734);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(10,6881.715);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(11,2359.81);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(13,2141.374);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(14,3136.015);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,70.77616);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,58.59428);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,62.2552);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,111.9725);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,114.9716);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,49.38932);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,49.8064);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(9,114.9407);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(10,112.6692);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(11,61.82171);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(13,59.31251);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(14,73.22474);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(117172.3);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#eta");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   Double_t xAxis131[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_tag_loose_os_peak_PeriodA_physics_Egamma = new TH1D("eta_data_tag_loose_os_peak_PeriodA_physics_Egamma","DATA",14, xAxis131);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(1,3038);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(2,1999);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(4,2358);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(5,7125);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(6,7584);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(7,1629);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(8,1567);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(9,7563);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(10,7087);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(11,2361);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(13,2115);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(14,3001);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(1,55.11806);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(2,44.71018);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(4,48.55924);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(5,84.40972);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(6,87.08616);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(7,40.36087);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(8,39.58535);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(9,86.96551);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(10,84.18432);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(11,48.59012);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(13,45.98913);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(14,54.78138);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetEntries(47467);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetStats(0);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#eta");
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->Draw("esame");
   
   TLegend *leg = new TLegend(0.6,0.6,0.75,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("eta_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.75,0.6,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("eta_data_temp_peak_tag_PeriodA_physics_Egamma","BKG","lf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.675,0.5,0.825,0.6,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("eta_data_tag_loose_os_peak_PeriodA_physics_Egamma","data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(-3.068788,0.3095238,2.919091,1.5);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0);
   c_2->SetBottomMargin(0.16);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis132[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_tag_loose_os_peak_PeriodA_physics_Egamma = new TH1D("eta_data_tag_loose_os_peak_PeriodA_physics_Egamma","DATA",14, xAxis132);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(1,1.008035);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.9463064);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(4,1.015325);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(5,1.041772);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(6,1.013389);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(7,1.057017);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.9884677);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(9,1.003618);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(10,1.029831);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(11,1.000504);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(13,0.9876837);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(14,0.9569469);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.02991453);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.03371884);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.0343214);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02105281);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.01943672);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.04281788);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.03984952);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(9,0.01917066);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(10,0.02083096);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(11,0.03333153);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(13,0.0347801);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(14,0.02836225);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetMinimum(0.5);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetMaximum(1.5);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetEntries(12758.6);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetStats(0);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#eta");
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.5);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("data/prediction");
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   eta_data_tag_loose_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis133[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("eta_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",14, xAxis133);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(9,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(10,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(11,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(13,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(14,1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,0.03321161);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,0.03922737);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,0.03790985);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,0.02315336);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,0.02172617);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,0.045322);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,0.04443178);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(9,0.02157065);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(10,0.02315387);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(11,0.03704921);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(13,0.03917138);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(14,0.03302134);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(10202.51);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#eta");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   eta_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   TLine *line = new TLine(-2.47,1,2.47,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
