{
//=========Macro generated from canvas: c/c
//=========  (Thu Jul 10 15:15:30 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(15909.09,-0.02365591,106818.2,1.15914);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0.02);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   Double_t xAxis9[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l = new TH1D("jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC",8, xAxis9);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(1,0.7944853);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(2,0.7880972);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(3,0.7776354);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(4,0.7666546);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(5,0.7643725);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(6,0.7691999);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(7,0.761955);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(8,0.7641474);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(1,0.005760932);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(2,0.005914897);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(3,0.006307776);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(4,0.006850761);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(5,0.00774034);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(6,0.006783007);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(7,0.007127446);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(8,0.007807735);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMinimum(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMaximum(1.1);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetEntries(115135);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetStats(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetFillStyle(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineColor(ci);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineStyle(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerColor(ci);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerStyle(22);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelSize(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleSize(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitle("Efficiency");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleSize(0.06);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleOffset(0.7);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->Draw("pe");
   Double_t xAxis10[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis10);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,0.789585);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.7840613);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.7862829);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,0.7760125);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.7639553);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.7615811);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,0.7552767);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.7350541);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.01513698);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.0148663);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.02263278);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.01793382);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02023722);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.02035821);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.02117437);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.0274685);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(17828.15);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetFillStyle(0);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineStyle(0);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMarkerStyle(23);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("Efficiency");
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("pesame");
   
   TLegend *leg = new TLegend(0.6,0.3,0.75,0.5,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma","data","lpe");
   entry->SetLineColor(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(23);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lpe");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(15909.09,0.6235294,106818.2,1.211765);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0.02);
   c_2->SetBottomMargin(0.3);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis11[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis11);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,0.9938322);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.994879);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,1.01112);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,1.012206);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.9994542);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.9900952);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,0.9912353);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.961927);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.02036989);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.02028761);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.03023816);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.02508011);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02834413);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.02786965);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.02929558);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.03726605);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMinimum(0.8);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMaximum(1.2);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(10211.12);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetFillStyle(0);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineStyle(0);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMarkerStyle(23);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.85);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("Data/MC");
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   jetpt_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis12[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l = new TH1D("jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC",8, xAxis12);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(1,1);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(2,1);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(3,1);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(4,1);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(5,1);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(6,1);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(7,1);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(8,1);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(1,0.01025467);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(2,0.01061408);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(3,0.01147137);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(4,0.01263729);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(5,0.01432089);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(6,0.01247091);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(7,0.01322878);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(8,0.01444984);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMinimum(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMaximum(1.1);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetEntries(51056.22);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetStats(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetFillStyle(0);

   ci = TColor::GetColor("#0000ff");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineColor(ci);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineStyle(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerColor(ci);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerStyle(22);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerSize(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitle("jet p_{T} [MeV]");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelSize(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleSize(0);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitle("Efficiency");
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleSize(0.06);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleOffset(0.7);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleSize(0.035);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleFont(42);
   jetpt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->Draw("e2same");
   TLine *line = new TLine(25000,1,100000,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
