{
//=========Macro generated from canvas: c/c
//=========  (Thu Jul 10 15:00:30 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(10483.87,-214.2,107258.1,10495.8);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetLeftMargin(0.15);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0.02);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   
   THStack *mc_pt = new THStack();
   mc_pt->SetName("mc_pt");
   mc_pt->SetTitle("mc_pt");
   mc_pt->SetMinimum(0);
   mc_pt->SetMaximum(9486);
   Double_t xAxis1[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1F *mc_pt_stack_1 = new TH1F("mc_pt_stack_1","mc_pt",8, xAxis1);
   mc_pt_stack_1->SetMinimum(0);
   mc_pt_stack_1->SetMaximum(9960.3);
   mc_pt_stack_1->SetDirectory(0);
   mc_pt_stack_1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   mc_pt_stack_1->SetLineColor(ci);
   mc_pt_stack_1->GetXaxis()->SetTitle("p_{T} [MeV]");
   mc_pt_stack_1->GetXaxis()->SetLabelFont(42);
   mc_pt_stack_1->GetXaxis()->SetLabelSize(0);
   mc_pt_stack_1->GetXaxis()->SetTitleSize(0);
   mc_pt_stack_1->GetXaxis()->SetTitleFont(42);
   mc_pt_stack_1->GetYaxis()->SetTitle("entries");
   mc_pt_stack_1->GetYaxis()->SetLabelFont(42);
   mc_pt_stack_1->GetYaxis()->SetLabelSize(0.035);
   mc_pt_stack_1->GetYaxis()->SetTitleSize(0.06);
   mc_pt_stack_1->GetYaxis()->SetTitleFont(42);
   mc_pt_stack_1->GetZaxis()->SetLabelFont(42);
   mc_pt_stack_1->GetZaxis()->SetLabelSize(0.035);
   mc_pt_stack_1->GetZaxis()->SetTitleSize(0.035);
   mc_pt_stack_1->GetZaxis()->SetTitleFont(42);
   mc_pt->SetHistogram(mc_pt_stack_1);
   
   Double_t xAxis2[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_temp_peak_tag_PeriodA_physics_Egamma__1 = new TH1D("pt_data_temp_peak_tag_PeriodA_physics_Egamma__1","BKG",8, xAxis2);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(1,6.97575);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(2,7.571398);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(3,-0.0894189);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(4,0.1714765);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(5,1.683664);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(6,0.04125046);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(7,1.312885);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinContent(8,0.9319038);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(1,3.000867);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(2,2.450491);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(3,0.08356787);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(4,0.8891959);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(5,1.027817);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(6,0.5997768);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(7,0.5006245);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetBinError(8,0.350353);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetEntries(19.65756);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetDirectory(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetLineColor(ci);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->SetLineWidth(2);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetXaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetXaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetXaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetXaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetYaxis()->SetTitle("entries");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetYaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetYaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetYaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetYaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetZaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetZaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetZaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma__1->GetZaxis()->SetTitleFont(42);
   mc_pt->Add(pt_data_temp_peak_tag_PeriodA_physics_Egamma,"");
   Double_t xAxis3[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2 = new TH1D("pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2","MC",8, xAxis3);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(1,9347.346);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(2,7830.393);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(3,4956.486);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(4,2895.819);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(5,1816.413);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(6,1776.517);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(7,1363.361);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinContent(8,998.6641);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(1,104.2017);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(2,95.12352);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(3,75.90879);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(4,57.64419);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(5,45.43324);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(6,36.61401);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(7,29.45063);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetBinError(8,24.7786);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetEntries(89215);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetDirectory(0);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetLineColor(ci);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->SetLineWidth(2);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetXaxis()->SetLabelFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetXaxis()->SetLabelSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetXaxis()->SetTitleSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetXaxis()->SetTitleFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetYaxis()->SetTitle("entries");
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetYaxis()->SetLabelFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetYaxis()->SetLabelSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetYaxis()->SetTitleSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetYaxis()->SetTitleFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetZaxis()->SetLabelFont(42);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetZaxis()->SetLabelSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetZaxis()->SetTitleSize(0.035);
   pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__2->GetZaxis()->SetTitleFont(42);
   mc_pt->Add(pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l,"");
   mc_pt->Draw("ehist");
   Double_t xAxis4[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("pt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis4);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,9354.322);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,7837.965);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,4956.397);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,2895.99);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,1818.096);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,1776.558);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1364.674);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,999.596);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,104.2449);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,95.15508);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,75.90884);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,57.65105);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,45.44486);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,36.61892);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,29.45488);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,24.78108);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(89234.66);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   Double_t xAxis5[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("pt_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis5);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,9486);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,7726);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,4781);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,3039);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,1862);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,1867);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,1354);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,870);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,97.3961);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,87.89767);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,69.14478);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,55.12713);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,43.1509);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,43.2088);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,36.79674);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,29.49576);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(31025);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("esame");
   
   TLegend *leg = new TLegend(0.6,0.6,0.75,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("pt_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.75,0.6,0.9,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("pt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.675,0.5,0.825,0.6,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("pt_data_tag_tight_os_peak_PeriodA_physics_Egamma","data","lpe");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(10483.87,0.05882352,107258.1,1.529412);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetLeftMargin(0.15);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0.02);
   c_2->SetBottomMargin(0.3);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis6[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("pt_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis6);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,1.014077);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.9857151);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.964612);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,1.049382);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,1.024148);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,1.050908);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,0.9921785);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.8703516);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.01536612);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.01640022);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.02031924);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.02826233);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.03490902);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.03256942);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.03443322);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.03655501);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMinimum(0.5);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMaximum(1.5);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(9699.899);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.75);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("data/prediction");
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   pt_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis7[9] = {25000, 30000, 35000, 40000, 45000, 50000, 60000, 80000, 100000}; 
   
   TH1D *pt_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("pt_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis7);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,0.01576005);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,0.01716895);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,0.02165914);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,0.02815303);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,0.03534947);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,0.02915017);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,0.03052414);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,0.0350599);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(10552.18);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("p_{T} [MeV]");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   pt_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   TLine *line = new TLine(25000,1,100000,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
