{
//=========Macro generated from canvas: c/c
//=========  (Thu Jul 10 15:00:25 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(0.1225806,-240.8,0.6387097,11799.2);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetLeftMargin(0.15);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0.02);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   
   THStack *mc_drjet = new THStack();
   mc_drjet->SetName("mc_drjet");
   mc_drjet->SetTitle("mc_drjet");
   mc_drjet->SetMinimum(0);
   mc_drjet->SetMaximum(10664);
   Double_t xAxis463[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1F *mc_drjet_stack_67 = new TH1F("mc_drjet_stack_67","mc_drjet",8, xAxis463);
   mc_drjet_stack_67->SetMinimum(0);
   mc_drjet_stack_67->SetMaximum(11197.2);
   mc_drjet_stack_67->SetDirectory(0);
   mc_drjet_stack_67->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   mc_drjet_stack_67->SetLineColor(ci);
   mc_drjet_stack_67->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   mc_drjet_stack_67->GetXaxis()->SetLabelFont(42);
   mc_drjet_stack_67->GetXaxis()->SetLabelSize(0);
   mc_drjet_stack_67->GetXaxis()->SetTitleSize(0);
   mc_drjet_stack_67->GetXaxis()->SetTitleFont(42);
   mc_drjet_stack_67->GetYaxis()->SetTitle("entries");
   mc_drjet_stack_67->GetYaxis()->SetLabelFont(42);
   mc_drjet_stack_67->GetYaxis()->SetLabelSize(0.035);
   mc_drjet_stack_67->GetYaxis()->SetTitleSize(0.06);
   mc_drjet_stack_67->GetYaxis()->SetTitleFont(42);
   mc_drjet_stack_67->GetZaxis()->SetLabelFont(42);
   mc_drjet_stack_67->GetZaxis()->SetLabelSize(0.035);
   mc_drjet_stack_67->GetZaxis()->SetTitleSize(0.035);
   mc_drjet_stack_67->GetZaxis()->SetTitleFont(42);
   mc_drjet->SetHistogram(mc_drjet_stack_67);
   
   Double_t xAxis464[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133 = new TH1D("drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133","BKG",8, xAxis464);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(1,4255.658);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(2,1462.209);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(3,599.4852);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(4,229.5565);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(5,171.0949);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(6,129.5003);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(7,161.6967);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(8,141.0524);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(1,85.41965);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(2,74.8635);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(3,59.40568);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(4,44.29294);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(5,52.93518);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(6,69.05603);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(7,83.38247);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(8,96.06647);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetEntries(1904.974);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetDirectory(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetLineColor(ci);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetLineWidth(2);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetXaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetXaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetXaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetXaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetYaxis()->SetTitle("entries");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetYaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetYaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetYaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetYaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetZaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetZaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetZaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetZaxis()->SetTitleFont(42);
   mc_drjet->Add(drjet_data_temp_peak_tag_PeriodA_physics_Egamma,"");
   Double_t xAxis465[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134 = new TH1D("drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134","MC",8, xAxis465);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(1,6281.925);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(2,5302.185);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(3,3444.797);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(4,1925.95);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(5,2834.61);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(6,4656.777);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(7,6637.234);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(8,8733.387);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(1,86.66908);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(2,74.84973);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(3,55.63227);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(4,37.69336);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(5,47.60986);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(6,67.11068);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(7,85.03965);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(8,104.8125);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetEntries(115135);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetDirectory(0);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetLineColor(ci);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetLineWidth(2);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetXaxis()->SetLabelFont(42);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetXaxis()->SetLabelSize(0.035);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetXaxis()->SetTitleSize(0.035);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetXaxis()->SetTitleFont(42);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetYaxis()->SetTitle("entries");
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetYaxis()->SetLabelFont(42);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetYaxis()->SetLabelSize(0.035);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetYaxis()->SetTitleSize(0.035);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetYaxis()->SetTitleFont(42);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetZaxis()->SetLabelFont(42);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetZaxis()->SetLabelSize(0.035);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetZaxis()->SetTitleSize(0.035);
   drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetZaxis()->SetTitleFont(42);
   mc_drjet->Add(drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l,"");
   mc_drjet->Draw("ehist");
   Double_t xAxis466[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("drjet_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis466);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,10537.58);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,6764.394);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,4044.283);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,2155.507);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,3005.705);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,4786.277);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,6798.931);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,8874.439);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,121.6883);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,105.8632);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,81.38786);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,58.16059);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,71.19573);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,96.29423);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,119.0982);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,142.1775);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(117040);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   Double_t xAxis467[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma = new TH1D("drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis467);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(1,10664);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(2,6699);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(3,3933);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(4,2097);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(5,2885);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(6,4838);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(7,7025);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(8,9286);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(1,103.2666);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(2,81.84742);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(3,62.71363);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(4,45.79301);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(5,53.7122);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(6,69.55573);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(7,83.81527);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(8,96.36389);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetEntries(47467);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetStats(0);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->Draw("esame");
   
   TLegend *leg = new TLegend(0.6,0.6,0.75,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("drjet_mc_tag_loose_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.75,0.6,0.9,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("drjet_data_temp_peak_tag_PeriodA_physics_Egamma","BKG","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.675,0.5,0.825,0.6,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma","data","lpe");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(0.1225806,0.05882352,0.6387097,1.529412);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetLeftMargin(0.15);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0.02);
   c_2->SetBottomMargin(0.3);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis468[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma = new TH1D("drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis468);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(1,1.011997);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.9903327);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.972484);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(4,0.9728571);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.9598415);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(6,1.010806);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(7,1.033251);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinContent(8,1.046376);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.01525165);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.01966255);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.0249692);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.03376974);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02891797);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.02499501);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.02189908);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.0199735);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetMinimum(0.5);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetMaximum(1.5);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetEntries(13544.91);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetStats(0);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.75);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("data/prediction");
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   drjet_data_tag_loose_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis469[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("drjet_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis469);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,0.01633138);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,0.02213254);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,0.02845989);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,0.03815877);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,0.03349829);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,0.0284523);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,0.02477305);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,0.02265713);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(10524);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   TLine *line = new TLine(0.2,1,0.6,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
