{
//=========Macro generated from canvas: c/c
//=========  (Thu Jul 10 15:00:36 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(0.1225806,-162.8742,0.6387097,7980.835);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetLeftMargin(0.15);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0.02);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   
   THStack *mc_drjet = new THStack();
   mc_drjet->SetName("mc_drjet");
   mc_drjet->SetTitle("mc_drjet");
   mc_drjet->SetMinimum(0);
   mc_drjet->SetMaximum(7213);
   Double_t xAxis463[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1F *mc_drjet_stack_67 = new TH1F("mc_drjet_stack_67","mc_drjet",8, xAxis463);
   mc_drjet_stack_67->SetMinimum(0);
   mc_drjet_stack_67->SetMaximum(7573.65);
   mc_drjet_stack_67->SetDirectory(0);
   mc_drjet_stack_67->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   mc_drjet_stack_67->SetLineColor(ci);
   mc_drjet_stack_67->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   mc_drjet_stack_67->GetXaxis()->SetLabelFont(42);
   mc_drjet_stack_67->GetXaxis()->SetLabelSize(0);
   mc_drjet_stack_67->GetXaxis()->SetTitleSize(0);
   mc_drjet_stack_67->GetXaxis()->SetTitleFont(42);
   mc_drjet_stack_67->GetYaxis()->SetTitle("entries");
   mc_drjet_stack_67->GetYaxis()->SetLabelFont(42);
   mc_drjet_stack_67->GetYaxis()->SetLabelSize(0.035);
   mc_drjet_stack_67->GetYaxis()->SetTitleSize(0.06);
   mc_drjet_stack_67->GetYaxis()->SetTitleFont(42);
   mc_drjet_stack_67->GetZaxis()->SetLabelFont(42);
   mc_drjet_stack_67->GetZaxis()->SetLabelSize(0.035);
   mc_drjet_stack_67->GetZaxis()->SetTitleSize(0.035);
   mc_drjet_stack_67->GetZaxis()->SetTitleFont(42);
   mc_drjet->SetHistogram(mc_drjet_stack_67);
   
   Double_t xAxis464[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133 = new TH1D("drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133","BKG",8, xAxis464);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(1,8.935805);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(2,1.254721);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(3,1.955756);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(4,0.7175455);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(5,0.791257);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(6,-0.6117679);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(7,6.928755);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinContent(8,6.214356);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(1,2.4781);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(2,1.082176);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(3,1.217345);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(4,0.7403812);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(5,0.9163651);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(6,1.209729);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(7,2.947558);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetBinError(8,2.989961);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetEntries(23.42505);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetDirectory(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetLineColor(ci);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->SetLineWidth(2);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetXaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetXaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetXaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetXaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetYaxis()->SetTitle("entries");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetYaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetYaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetYaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetYaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetZaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetZaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetZaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma__133->GetZaxis()->SetTitleFont(42);
   mc_drjet->Add(drjet_data_temp_peak_tag_PeriodA_physics_Egamma,"");
   Double_t xAxis465[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134 = new TH1D("drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134","MC",8, xAxis465);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(1,4394.46);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(2,3930.86);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(3,2702.809);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(4,1556.79);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(5,2266.057);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(6,3749.55);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(7,5359.86);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinContent(8,7024.613);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(1,69.82035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(2,62.47876);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(3,47.83084);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(4,33.72113);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(5,41.91284);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(6,58.5982);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(7,74.27949);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetBinError(8,90.52172);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetEntries(89215);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetDirectory(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetLineColor(ci);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->SetLineWidth(2);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetXaxis()->SetLabelFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetXaxis()->SetLabelSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetXaxis()->SetTitleSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetXaxis()->SetTitleFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetYaxis()->SetTitle("entries");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetYaxis()->SetLabelFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetYaxis()->SetLabelSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetYaxis()->SetTitleSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetYaxis()->SetTitleFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetZaxis()->SetLabelFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetZaxis()->SetLabelSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetZaxis()->SetTitleSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l__134->GetZaxis()->SetTitleFont(42);
   mc_drjet->Add(drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l,"");
   mc_drjet->Draw("ehist");
   Double_t xAxis466[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("drjet_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis466);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,4403.396);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,3932.115);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,2704.765);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,1557.508);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,2266.848);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,3748.938);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,5366.789);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,7030.828);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,69.86432);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,62.48813);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,47.84632);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,33.72926);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,41.92286);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,58.61069);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,74.33795);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,90.57109);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(89238.43);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   Double_t xAxis467[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis467);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,4512);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,3924);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,2612);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,1500);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,2110);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,3699);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,5415);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,7213);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,67.17142);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,62.64184);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,51.10773);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,38.72983);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,45.93474);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,60.8194);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,73.58668);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,84.92938);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(31025);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("esame");
   
   TLegend *leg = new TLegend(0.6,0.6,0.75,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.75,0.6,0.9,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("drjet_data_temp_peak_tag_PeriodA_physics_Egamma","BKG","lfe");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   leg = new TLegend(0.675,0.5,0.825,0.6,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma","data","lpe");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(0.1225806,0.05882352,0.6387097,1.529412);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetLeftMargin(0.15);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0.02);
   c_2->SetBottomMargin(0.3);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis468[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis468);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,1.024664);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.9979362);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.9657032);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,0.9630772);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.9308077);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.9866793);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,1.008983);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,1.025911);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.02229348);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.02247881);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.02547283);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.03245507);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.0265885);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.02238617);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.01957884);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.01790455);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMinimum(0.5);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMaximum(1.5);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(13531.82);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.75);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("data/prediction");
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis469[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_temp_peak_tag_PeriodA_physics_Egamma = new TH1D("drjet_data_temp_peak_tag_PeriodA_physics_Egamma","BKG",8, xAxis469);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(1,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(2,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(3,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(4,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(5,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(6,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(7,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinContent(8,1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(1,0.02243793);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(2,0.02247431);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(3,0.02501693);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(4,0.0306261);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(5,0.02615432);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(6,0.02210973);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(7,0.01958895);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetBinError(8,0.01821789);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetEntries(14346.99);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetStats(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillColor(1);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetFillStyle(3004);

   ci = TColor::GetColor("#ff0000");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineColor(ci);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineStyle(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetLineWidth(2);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->SetMarkerStyle(0);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitle("entries");
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   drjet_data_temp_peak_tag_PeriodA_physics_Egamma->Draw("e2same");
   TLine *line = new TLine(0.2,1,0.6,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
