{
//=========Macro generated from canvas: c/c
//=========  (Thu Jul 10 15:15:30 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(0.1515152,-0.02365591,0.6363636,1.15914);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0.02);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   Double_t xAxis13[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l = new TH1D("drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC",8, xAxis13);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(1,0.6995403);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(2,0.7413662);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(3,0.7846061);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(4,0.8083231);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(5,0.7994247);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(6,0.8051814);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(7,0.8075442);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(8,0.8043401);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(1,0.007054417);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(2,0.006609831);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(3,0.007154954);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(4,0.008332373);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(5,0.007467613);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(6,0.006191404);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(7,0.006219707);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(8,0.00536315);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMinimum(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMaximum(1.1);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetEntries(115135);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetStats(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetFillStyle(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineColor(ci);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineStyle(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerColor(ci);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerStyle(22);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelSize(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleSize(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitle("Efficiency");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleSize(0.06);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleOffset(0.7);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->Draw("pe");
   Double_t xAxis14[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis14);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,0.7026878);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.7490743);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.7829707);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,0.8028529);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.7771859);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.7857305);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,0.7879691);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.788062);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.03877472);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.0256164);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.01989753);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.0292445);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02235237);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.01398656);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.01093449);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.009741991);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(18110.91);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetFillStyle(0);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineStyle(0);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMarkerStyle(23);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("Efficiency");
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("pesame");
   
   TLegend *leg = new TLegend(0.6,0.3,0.75,0.5,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma","data","lpe");
   entry->SetLineColor(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(23);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lpe");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(0.1515152,0.6235294,0.6363636,1.211765);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0.02);
   c_2->SetBottomMargin(0.3);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis15[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",8, xAxis15);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,1.004499);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,1.010397);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(3,0.9979156);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,0.9932327);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.9721814);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.9758428);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,0.9757598);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.9797622);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.05634687);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.03570798);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(3,0.02694322);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.03760002);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02939838);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.01892211);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.01548622);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.01376129);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMinimum(0.8);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMaximum(1.2);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(7591.293);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetFillStyle(0);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineStyle(0);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMarkerStyle(23);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.85);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("Data/MC");
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   drjet_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis16[9] = {0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6}; 
   
   TH1D *drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l = new TH1D("drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC",8, xAxis16);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(1,1);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(2,1);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(3,1);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(4,1);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(5,1);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(6,1);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(7,1);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(8,1);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(1,0.01426144);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(2,0.01260877);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(3,0.01289645);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(4,0.01457803);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(5,0.0132105);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(6,0.01087453);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(7,0.01089228);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(8,0.009429642);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMinimum(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMaximum(1.1);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetEntries(51548.91);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetStats(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetFillStyle(0);

   ci = TColor::GetColor("#0000ff");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineColor(ci);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineStyle(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerColor(ci);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerStyle(22);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerSize(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitle("#DeltaR(e, jet)");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelSize(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleSize(0);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitle("Efficiency");
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleSize(0.06);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleOffset(0.7);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleSize(0.035);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleFont(42);
   drjet_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->Draw("e2same");
   TLine *line = new TLine(0.2,1,0.6,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
