{
//=========Macro generated from canvas: c/c
//=========  (Thu Jul 10 15:15:29 2014) by ROOT version5.34/18
   TCanvas *c = new TCanvas("c", "c",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_1
   TPad *c_1 = new TPad("c_1", "c_1",0,0.32,1,1);
   c_1->Draw();
   c_1->cd();
   c_1->Range(-3.068788,-0.02365591,2.919091,1.15914);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetTickx(1);
   c_1->SetTicky(1);
   c_1->SetRightMargin(0.075);
   c_1->SetTopMargin(0.05);
   c_1->SetBottomMargin(0.02);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   Double_t xAxis5[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l = new TH1D("eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC",14, xAxis5);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(1,0.7655587);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(2,0.7474687);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(4,0.7376802);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(5,0.7845004);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(6,0.811798);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(7,0.7293202);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(8,0.70406);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(9,0.8034857);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(10,0.7900132);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(11,0.7429292);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(13,0.7524522);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(14,0.7717064);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(1,0.007965116);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(2,0.01013599);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(4,0.009366124);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(5,0.006658953);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(6,0.005668365);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(7,0.01158178);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(8,0.01227883);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(9,0.005819698);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(10,0.006522169);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(11,0.009061449);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(13,0.009593123);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(14,0.008594497);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMinimum(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMaximum(1.1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetEntries(115141);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetStats(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetFillStyle(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineColor(ci);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineStyle(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerColor(ci);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerStyle(22);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitle("#eta");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelSize(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleSize(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitle("Efficiency");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleSize(0.06);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleOffset(0.7);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->Draw("pe");
   Double_t xAxis6[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("eta_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",14, xAxis6);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,0.7175671);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.7377895);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,0.7525782);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.7842425);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.7869311);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,0.7441151);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,0.7080596);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(9,0.7945106);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(10,0.7737902);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(11,0.768405);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(13,0.7643678);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(14,0.7442844);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.01908519);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.02521601);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.0324219);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.01902813);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.02963377);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.02644922);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.0412078);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(9,0.02406326);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(10,0.0258346);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(11,0.02147864);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(13,0.02298562);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(14,0.01978099);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(18127.43);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetFillStyle(0);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineStyle(0);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMarkerStyle(23);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#eta");
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("Efficiency");
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("pesame");
   
   TLegend *leg = new TLegend(0.6,0.3,0.75,0.5,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(ci);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("eta_data_tag_tight_os_peak_PeriodA_physics_Egamma","data","lpe");
   entry->SetLineColor(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(23);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC","lpe");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   c_1->Modified();
   c->cd();
  
// ------------>Primitives in pad: c_2
   c_2 = new TPad("c_2", "c_2",0,0.05,1,0.3);
   c_2->Draw();
   c_2->cd();
   c_2->Range(-3.068788,0.6235294,2.919091,1.211765);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetTickx(1);
   c_2->SetTicky(1);
   c_2->SetRightMargin(0.075);
   c_2->SetTopMargin(0.02);
   c_2->SetBottomMargin(0.3);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   Double_t xAxis7[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_data_tag_tight_os_peak_PeriodA_physics_Egamma = new TH1D("eta_data_tag_tight_os_peak_PeriodA_physics_Egamma","DATA",14, xAxis7);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(1,0.9373116);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(2,0.9870506);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(4,1.020196);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(5,0.9996713);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(6,0.9693682);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(7,1.020286);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(8,1.005681);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(9,0.9888298);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(10,0.9794649);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(11,1.034291);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(13,1.015836);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinContent(14,0.9644659);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(1,0.02676931);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(2,0.03629349);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(4,0.04582017);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(5,0.02569651);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(6,0.03712609);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(7,0.03972039);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(8,0.06110026);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(9,0.03079308);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(10,0.03368641);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(11,0.03154321);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(13,0.0331796);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetBinError(14,0.02779235);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMinimum(0.8);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMaximum(1.2);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetEntries(8649.345);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetStats(0);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetFillStyle(0);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineStyle(0);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetLineWidth(2);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->SetMarkerStyle(23);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitle("#eta");
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetLabelSize(0.1);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleSize(0.15);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleOffset(0.85);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetXaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitle("Data/MC");
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetNdivisions(205);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetLabelSize(0.1);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleSize(0.15);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleOffset(0.25);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetYaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetLabelSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleSize(0.035);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->GetZaxis()->SetTitleFont(42);
   eta_data_tag_tight_os_peak_PeriodA_physics_Egamma->Draw("e");
   Double_t xAxis8[15] = {-2.47, -1.81, -1.52, -1.37, -1.15, -0.6, -0.1, 0, 0.1, 0.6, 1.15, 1.37, 1.52, 1.81, 2.47}; 
   
   TH1D *eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l = new TH1D("eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l","MC",14, xAxis8);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(1,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(2,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(4,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(5,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(6,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(7,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(8,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(9,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(10,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(11,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(13,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinContent(14,1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(1,0.01471393);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(2,0.01917733);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(4,0.01795588);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(5,0.01200405);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(6,0.009874722);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(7,0.02245805);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(8,0.02466392);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(9,0.01024324);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(10,0.01167542);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(11,0.01724905);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(13,0.01803001);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetBinError(14,0.0157501);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMinimum(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMaximum(1.1);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetEntries(42693.48);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetStats(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetFillStyle(0);

   ci = TColor::GetColor("#0000ff");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineColor(ci);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineStyle(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerColor(ci);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerStyle(22);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->SetMarkerSize(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitle("#eta");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetLabelSize(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleSize(0);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetXaxis()->SetTitleFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitle("Efficiency");
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetLabelSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleSize(0.06);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleOffset(0.7);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetYaxis()->SetTitleFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetLabelSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleSize(0.035);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->GetZaxis()->SetTitleFont(42);
   eta_mc_tag_tight_os_peak_AcerMCPythia_P2011CCTEQ6L1_singletop_tchan_l->Draw("e2same");
   TLine *line = new TLine(-2.47,1,2.47,1);
   line->SetLineStyle(7);
   line->Draw();
   c_2->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
